sudo: false

language: go
go:
  - 1.6
  - tip

install:
  - go get golang.org/x/tools/cmd/vet

script:
  - "! gofmt -l $(find . -path ./vendor -prune -o -name '*.go' -print) | read nothing"
  - go vet
  - go test -v -cover
  - go build
